### ISSUE TITLE
Create SkillDetail screen

### ISSUE THREAD

**Issue by interaminense** [liferay-labs-br/liferay-grow#102]
- [x] Create Header
- [x] Create Mentors
- [x] Add Total members
- [x] Create Summary

**Comment by interaminense** [comment]
@kevenleone I reopened this problem because some topics are missing.

**Comment by kevenleone** [comment]
Oh, sorry didi, I didn't noted

**Comment by interaminense** [comment]
@kevenleone I used `recharts` to implement the donut. I think we can adopt recharts to implement our charts

**Comment by kevenleone** [comment]
No problem, thanks @interaminense
