### ISSUE TITLE
Proposal: "Add more skills" option to always be shown when typing a skill, except when the regex search is a perfect match (no case sensitive)

### ISSUE THREAD

**Issue by mateusmeloxyz** [liferay-labs-br/liferay-grow#124]
When searching for a skill which doesn't exist in the database yet but the `string` of the new skill to be added is part of a `string` of an already present skill, the option to add this new skill isn't available.

Examples:

When trying to add the skill `vi`, the option to add it as a new skill isn't available:
![Screenshot from 2021-03-25 21-12-22](https://user-images.githubusercontent.com/52260710/112559574-01452000-8db0-11eb-87d1-ddf767b76928.png)

I can only add `vim` as a new skill, since there's no match for the sequence `vim` in the current skills database.
![Screenshot from 2021-03-25 21-15-11](https://user-images.githubusercontent.com/52260710/112559582-03a77a00-8db0-11eb-9686-31a5d2c0e0cd.png)

Proposal:
- Make it so that the option to "Add more skills" is always displayed when searching for a skill, except for when there's a perfect match of the regex search (no case sensitive, to avoid duplicates).

**Comment by kevenleone** [comment]
cc: @interaminense, @victorctrl

**Comment by victorctrl** [comment]
I think this a great idea and cover an unmapped scenario.

**Comment by interaminense** [comment]
It looks good to me, it's a good approach

**Comment by kevenleone** [comment]
Would you like to implement this feature, @mateusgomes01 ?

Isn't completed yet, you could use this mock 

https://www.figma.com/file/RroxXVwPoQgvylmehEjBOG/engineering-grow-together?node-id=961%3A45987

We have few days to deliver this feature, tell me if you can, thanks!

**Comment by mateusmeloxyz** [comment]
@kevenleone 

I don't have much experience but I would love to try! I may need help but I'll do my best!

**Comment by kevenleone** [comment]
Okay thanks 👋🏻 

I'll be here, if you need me

**Comment by kevenleone** [comment]
Fixed in Issue #139 and Pull Request #140

**Comment by kevenleone** [comment]
@mateusgomes01 i had to do this change, because we are running out of time, and we need to deliver this week, feel free to collaborate with another issue or task, thanks man!
